apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: booking-system
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: IMAGE_TAG
          ports:
            - containerPort: 8080
